// <auto-generated />
using FEAasp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FEAasp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FEAasp.Models.contatos", b =>
                {
                    b.Property<int>("idContato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idContato"));

                    b.Property<string>("emailcontato")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("mensagem")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nomeContato")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("telefoneContato")
                        .HasColumnType("int");

                    b.HasKey("idContato");

                    b.ToTable("contato");
                });
#pragma warning restore 612, 618
        }
    }
}
